export const enemies = [

    {
        name: 'Ibis',
        imageSource: 'assets/units/enemies/ibis.png',
        avatar: 'assets/units/enemies/avatars/ibis.png',
        value: 70,
        difficult: 'weak',
        shield: 0,
        maxHp: 70,
        speed: 2,
        minAttack: 30,
        maxAttack: 40,
        intelligence: 0,
        criticalChance: 0,
        strength: 0,
        resistance: 0,
        magicResistance: 0,
        skills: ['attack']
    },
    {
        name: 'Leprechaun',
        imageSource: require('../../assets/units/forest/leprechaun.png'),
        avatar: require('../../assets/units/avatars/leprechaun.png'),
        value: 85,
        difficult: 'weak',
        shield: 0,
        maxHp: 80,
        speed: 5,
        minAttack: 35,
        maxAttack: 45,
        intelligence: 0,
        criticalChance: 20,
        strength: 0,
        resistance: 0,
        magicResistance: 0,
        skills: ['attack', 'Gold Coin Toss']
    },
    {
        name: 'Forest Tree',
        imageSource: require('../../assets/units/forest/forestTree.png'),
        avatar: require('../../assets/units/avatars/forestTree.png'),
        value: 85,
        difficult: 'weak',
        shield: 0,
        maxHp: 100,
        speed: 3,
        minAttack: 30,
        maxAttack: 35,
        intelligence: 0,
        criticalChance: 0,
        strength: 0,
        resistance: 5,
        magicResistance: 0,
        skills: ['attack', 'Root Strike']
    },
    {
        name: 'Forest Snake',
        imageSource: require('../../assets/units/forest/forestSnake.png'),
        avatar: require('../../assets/units/avatars/forestSnake.png'),
        value: 90,
        difficult: 'weak',
        shield: 0,
        maxHp: 70,
        speed: 4,
        minAttack: 40,
        maxAttack: 45,
        intelligence: 0,
        criticalChance: 0,
        strength: 0,
        resistance: 0,
        magicResistance: 3,
        skills: ['attack', 'Venomous Bite']
    },
    {
        name: 'Dryad',
        imageSource: require('../../assets/units/forest/dryad.png'),
        avatar: require('../../assets/units/avatars/dryad.png'),
        value: 100,
        difficult: 'weak',
        shield: 0,
        maxHp: 85,
        speed: 6,
        minAttack: 40,
        maxAttack: 40,
        intelligence: 0,
        criticalChance: 10,
        strength: 5,
        resistance: 0,
        magicResistance: 0,
        skills: ['attack', 'Forest\'s Fury']
    },
]